apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-ddnsnow
  namespace: certbot
spec:
  schedule: "0 0 */30 * *"  # 30日に1回
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: certs
              persistentVolumeClaim:
                claimName: certbot-pvc
            - name: ddns-secret
              secret:
                secretName: ddns-now-secret
          containers:
            - name: certbot
              image: certbot/certbot:latest
              volumeMounts:
                - name: certs
                  mountPath: /etc/letsencrypt
                - name: ddns-secret
                  mountPath: /etc/secrets
                  readOnly: true
              env:
                - name: DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: ddns-now-secret
                      key: DOMAIN
                - name: EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ddns-now-secret
                      key: EMAIL
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ddns-now-secret
                      key: USERNAME
                - name: API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ddns-now-secret
                      key: API_TOKEN
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /root/.ddnsnow
                  # 1. 公式スクリプトを wget で取得
                  wget -O /root/.ddnsnow/DDNSNowAcmeSetup.sh "https://ddns.kuku.lu/files/DDNSNowAcmeSetup.txt"
                  chmod +x /root/.ddnsnow/DDNSNowAcmeSetup.sh
                  # 2. 認証スクリプト作成
                  cat <<EOF >/root/.ddnsnow/setup.sh
                  #!/bin/sh
                  export DDNSNOW_USER=${USERNAME}
                  export DDNSNOW_API_TOKEN=${API_TOKEN}
                  /bin/sh /root/.ddnsnow/DDNSNowAcmeSetup.sh \$CERTBOT_DOMAIN \$DDNSNOW_API_TOKEN
                  EOF
                  ls -l  /root/.ddnsnow/
                  chmod +x /root/.ddnsnow/DDNSNowAcmeAuthHook.sh
                  # 3. 証明書の取得
                  certbot certonly \
                    --server https://acme-staging-v02.api.letsencrypt.org/directory \
                    --manual \
                    --preferred-challenges dns \
                    --manual-auth-hook /root/.ddnsnow/DDNSNowAcmeAuthHook.sh \
                    -d $DOMAIN \
                    --agree-tos \
                    -m $EMAIL \
                    --keep-until-expiring
                  # 4. nginx 再読込
                  pkill -HUP nginx || true
