apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-configs
data:
  mc-whitelist.json: |
    [
      {
        "uuid": "a4ea87de-f923-4889-9bd2-7d4899803d2d",
        "name": "latch1225"
      },
      {
        "uuid": "ebd6ed5c-7a32-49fd-b287-df57f2ffb33b",
        "name": "maron_12345"
      },
      {
        "uuid": "00000000-0000-0000-0009-01f15afac14e",
        "name": "geyser.HarshPilot62425"
      },
      {
        "uuid": "00000000-0000-0000-0009-01f18712bd98",
        "name": "geyser.sasasagi"
      },
      {
        "uuid": "00000000-0000-0000-0009-01ff6a486e30",
        "name": "geyser.maron3716"
      },
      {
        "uuid": "76494c80-12a0-4414-82a0-1be7fa57fb5f",
        "name": "haramiten"
      }
    ]
