apiVersion: apps/v1
kind: Deployment
metadata:
  name: geyser-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geyser-standalone
  template:
    metadata:
      labels:
        app: geyser-standalone
    spec:
      containers:
        - name: geyser-standalone
          image: portiz93/geysermc-proxy:latest
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: BEDROCK_ADDRESS
              value: 0.0.0.0
            - name: BEDROCK_PORT
              value: "53617"
            - name: JAVA_ADDRESS
              value: 192.168.15.200
            - name: JAVA_PORT
              value: "53616"
            - name: JAVA_AUTH_TYPE
              value: "floodgate"
          ports:
            - containerPort: 53617
              protocol: UDP
              
          volumeMounts:
            # ------- key-pem mount -------
            - name: key-pem
              mountPath: /Geyser/floodgate/key.pem
              subPath: key.pem

      volumes:
        # key-pemの永続ストレージの指定
        - name: key-pem
          persistentVolumeClaim:
            claimName: floodgate-pvc