apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-proxy
  labels:
    app: mc-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mc-proxy
  template:
    metadata:
      labels:
        app: mc-proxy
    spec:
      initContainers:
        # initcontainersでサーバーアイコンをダウンロード
        - name: server-icon-downloader
          image: busybox:1.36.1
          env:
            # serverアイコンのダウンロードURL
            - name: SERVER_ICON_URL
              value: "https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/a47b0c0ad303f248f1d50a7b5b3ac508f4435389/minecraft/branding/server-icon.png" #  サーバーのアイコン画像取得pathを投入
          volumeMounts:
            - name: server-icon-download-volume
              mountPath: /root/server-icon-download
          command:
            - "sh"
            - "-c"
            - 'wget -O /root/server-icon-download/server-icon.png "${SERVER_ICON_URL}"'
        # initcontainersでpluginファイルをダウンロード
        - name: plugin-downloader
          image: busybox:1.36.1
          env:
            # GEYSER_MCのダウンロードURL
            - name: GEYSER_URL
              value: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity"
            # FLOODGATE_MCのダウンロードURL
            - name: FLOODGATE_URL
              value: "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity"
          volumeMounts:     
            - name: ini-plugin-download-volume
              mountPath: /root/ini-plugin-download
          command:
            - sh
            - -c
            - >
              wget -O /root/ini-plugin-download/geyser-velocity.jar "${GEYSER_URL}" &&
              wget -O /root/ini-plugin-download/floodgate-velocity.jar "${FLOODGATE_URL}"
      nodeSelector:
        kubernetes.io/hostname: onp-k8s-wk-3
      containers:
        - image: itzg/bungeecord:latest
          name: mc-proxy
          resources:
            requests:
              memory: "768Mi"
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: VELOCITY
            - name: MEMORY
              value: "768m"
            - name: PLUGINS
              # commander-velocity
              # bungeecord-prometheus-exporter
              # BanManagerBungeeCord
              # LuckPerms-Velocity
              # GeyserSkinManager-Velocity
              # minimotd-velocity
              # ViaVersion
              # VelocityRcon
              value: >-
                https://hangarcdn.papermc.io/plugins/TheNextLvl/CommandControl/versions/4.4.0/VELOCITY/commander-velocity-4.4.0-all.jar,
                https://github.com/weihao/bungeecord-prometheus-exporter/releases/download/3.2.7/bungeecord-prometheus-exporter-3.2.7.jar,
                https://ci.frostcast.net/job/BanManager/lastSuccessfulBuild/artifact/velocity/build/libs/BanManagerVelocity.jar,
                https://download.luckperms.net/1595/velocity/LuckPerms-Velocity-5.5.10.jar,
                https://github.com/Camotoy/GeyserSkinManager/releases/download/1.8/GeyserSkinManager-Velocity.jar,
                https://hangarcdn.papermc.io/plugins/jmp/MiniMOTD/versions/2.1.7/VELOCITY/minimotd-velocity-2.1.7.jar,
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.2/PAPER/ViaVersion-5.4.2.jar,
                https://cdn.modrinth.com/data/KkmSfl3v/versions/LsmNou60/Velocircon-1.0.2.jar
            - name: SPIGET_PLUGINS
              value: 
          ports:
            - containerPort: 25577
              name: proxy-service
              protocol: TCP
            - containerPort: 19132
              name: geyser-service
              protocol: UDP
          startupProbe:
            tcpSocket:
              port: 25577
            # 最大120秒待つ
            failureThreshold: 6
            periodSeconds: 20
          volumeMounts:
            # サーバーアイコンファイルのマウント設定
            - name: server-icon-download-volume
              mountPath: /config/server-icon.png
              subPath: server-icon.png

            # init downloadファイルのマウント
            - name: ini-plugin-download-volume
              mountPath: /server/plugins/geyser-velocity.jar
              subPath: geyser-velocity.jar
            - name: ini-plugin-download-volume
              mountPath: /server/plugins/floodgate-velocity.jar
              subPath: floodgate-velocity.jar
      volumes:
        # geyser-velocity.jarとfloodgate-velocity.jarをinitContainerでダウンロードしてvelocityに受け渡すためのvolume
        - name: ini-plugin-download-volume
          emptyDir: {}
        # サーバーアイコンをinitContainerでダウンロードしてvelocityに受け渡すためのvolume
        - name: server-icon-download-volume
          emptyDir: {}
