apiVersion: v1
kind: Service
metadata:
  name: mc-proxy-lb
  labels:
    app: mc-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.15.70
  ports:
    - name: java-service
      port: 53616
      protocol: TCP
      targetPort: proxy-service
    - name: bedrock-service
      port: 53617
      protocol: UDP
      targetPort: geyser-service
  selector:
    app: mc-proxy
