apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/server.conf
              subPath: nginx-server.conf
            - name: nginx-guide
              mountPath: /usr/share/nginx/html/guide.html
              subPath: guide.html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-guide
          configMap:
            name: nginx-html-guide
