apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
resources:
  # templates
  - ../../templates/nginx-proxy
  # service
  - svc-LoadBalancer.yaml
  # config
  - config/nginx-harami-config.yaml
