apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
resources:
  # templates
  - ../../templates/nginx-proxy
  - ./config/hp-html.yaml
patches:
  - path: svc-LoadBalancer.yaml
  - path: config/nginx-harami-config.yaml
