apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mc-haramis
data:
  nginx.conf: |
    events {}

    http {
        include       mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            server_name _;

            root /usr/share/nginx/html;
            index index.html;

            # BlueMap for s1
            location /bluemap/s1/ {
                rewrite ^/bluemap/s1/(.*)$ /$1 break;

                proxy_pass http://mc-s1-mc-s1map-service.mc-haramis.svc.cluster.local:8100/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }
    }
