apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mc-haramis
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log /var/log/nginx/error.log warn;
    pid       /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile      on;
        keepalive_timeout 65;

        include /etc/nginx/conf.d/*.conf;
    }
