apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ja">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>はら民限定マインクラフトサーバー</title>
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, sans-serif;
          background: linear-gradient(135deg, #1a1a1a, #2c2c2c);
          color: #fff;
          text-align: center;
          padding: 40px;
          margin: 0;
        }
        h1 {
          font-size: 2.5em;
          margin-bottom: 10px;
          color: #ffcc00;
        }
        p {
          font-size: 1.2em;
          margin-bottom: 30px;
          color: #ccc;
        }
        .container {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 15px;
        }
        .link-btn {
          display: inline-block;
          width: 80%;
          max-width: 400px;
          padding: 15px 20px;
          font-size: 1.2em;
          color: #1a1a1a;
          background: #ffcc00;
          text-decoration: none;
          border-radius: 10px;
          font-weight: bold;
          transition: transform 0.2s, background 0.3s;
        }
        .link-btn:hover {
          transform: scale(1.05);
          background: #ffd633;
        }
        footer {
          margin-top: 50px;
          font-size: 0.9em;
          color: #777;
        }
      </style>
    </head>
    <body>
      <h1>ようこそ はら民限定MCサーバーへ</h1>
      <p>配信者「はらみ」のサブスク限定マインクラフトサーバー紹介サイト</p>
      <div class="container">
        <a href="#join" class="link-btn">マインクラフトの入り方</a>
        <a href="#rules" class="link-btn">サーバー内のルール</a>
        <a href="/bluemap" class="link-btn">ワールドマップ</a>
        <a href="https://www.tiktok.com/@harami" target="_blank" class="link-btn">TikTokアカウント</a>
        <a href="https://x.com/harami" target="_blank" class="link-btn">X(旧Twitter)</a>
        <a href="https://lit.link/harami" target="_blank" class="link-btn">lit.link</a>
        <a href="https://discord.gg/harami" target="_blank" class="link-btn">サブスク限定Discord</a>
        <a href="https://www.amazon.jp/hz/wishlist" target="_blank" class="link-btn">Amazonほしい物リスト</a>
      </div>
      <footer>© 2025 Harami Server. All Rights Reserved.</footer>
    </body>
    </html>
