apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ja">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>はら民限定マイクラサーバー</title>
      <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-700 text-white flex flex-col items-center justify-center min-h-screen p-6">
      <h1 class="text-3xl font-bold mb-4 text-center">ようこそ はら民限定マインクラフトサーバーへ</h1>
      <p class="text-center mb-8 max-w-xl text-gray-300">
        本サイトは配信者「はらみ」のサブスク限定マイクラサーバーの紹介ページです。以下のメニューから詳細を確認してください。
      </p>

      <div id="links" class="flex flex-col gap-4 w-64"></div>

      <footer class="mt-12 text-gray-400 text-sm">© 2025 はらみサーバー</footer>

      <script>
        fetch('/links/links.json')
          .then(res => res.json())
          .then(links => {
            const container = document.getElementById('links');
            links.forEach(link => {
              const a = document.createElement('a');
              a.href = link.url;
              a.className = 'flex items-center gap-3 justify-start bg-blue-600 hover:bg-blue-700 rounded-xl py-3 px-4 text-white font-semibold transition-all duration-200';
              a.innerHTML = `<img src="${link.icon}" class="w-6 h-6" alt="${link.name}">${link.name}`;
              container.appendChild(a);
            });
          });
      </script>
    </body>
    </html>
