apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ja">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>はら民限定マイクラサーバー</title>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
      <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
      <style>
        body {
          margin: 0;
          font-family: 'Noto Sans JP', sans-serif;
          background: linear-gradient(135deg, #0f172a, #1e293b);
          color: #fff;
          text-align: center;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          min-height: 100vh;
          padding: 20px;
        }
        h1 { font-size: 2rem; margin-bottom: 10px; }
        p { max-width: 600px; margin-bottom: 40px; font-size: 1rem; line-height: 1.6; }
        .links {
          display: flex;
          flex-direction: column;
          gap: 15px;
          align-items: center;
          width: 250px; /* 横幅統一 */
        }
        .link-btn {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 10px;
          width: 100%; /* 横幅統一 */
          background: #2563eb;
          color: #fff;
          text-decoration: none;
          padding: 15px 0;
          border-radius: 12px;
          font-size: 1rem;
          font-weight: bold;
          transition: background 0.3s ease, transform 0.2s ease;
        }
        .link-btn:hover { background: #1d4ed8; transform: translateY(-2px); }
        .link-btn i { font-size: 1.2rem; }
        footer { margin-top: 40px; font-size: 0.9rem; color: #94a3b8; }
      </style>
    </head>
    <body>
      <h1>ようこそ はら民限定マインクラフトサーバーへ</h1>
      <p>本サイトは配信者「はらみ」のサブスク限定マイクラサーバーの紹介ページです。<br>
      以下のメニューから詳細を確認してください。</p>

      <div class="links">
        <a href="/guide" class="link-btn"><i class="fas fa-gamepad"></i> マイクラの入り方</a>
        <a href="/rules" class="link-btn"><i class="fas fa-scroll"></i> サーバー内のルール</a>
        <a href="/bluemap" class="link-btn"><i class="fas fa-map"></i> ワールドマップ</a>
        <a href="https://www.tiktok.com/@harami" class="link-btn"><i class="fab fa-tiktok"></i> TikTokアカウント</a>
        <a href="https://x.com/harami" class="link-btn"><i class="fab fa-x-twitter"></i> X(旧Twitter)</a>
        <a href="https://lit.link/harami" class="link-btn"><i class="fas fa-link"></i> lit.link</a>
        <a href="https://discord.gg/xxxxxx" class="link-btn"><i class="fab fa-discord"></i> Discordサーバー</a>
        <a href="https://www.amazon.jp/hz/wishlist/ls/xxxxxx" class="link-btn"><i class="fab fa-amazon"></i> Amazonほしい物リスト</a>
      </div>

      <footer>© 2025 はらみサーバー</footer>
    </body>
    </html>
