apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-guide
data:
  guide.html: |
    <!DOCTYPE html>
    <html lang="ja">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>マイクラサーバー接続ガイド</title>
      <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-700 text-white flex flex-col items-center justify-start min-h-screen p-6">
      <h1 class="text-3xl font-bold mb-4 text-center">マインクラフト サーバー接続方法</h1>
      <p class="text-center mb-8 max-w-xl text-gray-300">
        以下の手順に従って、Java版または統合版からサーバーに接続してください。
      </p>

      <!-- Java版 -->
      <section class="bg-gray-800 rounded-xl shadow-lg p-6 mb-8 max-w-2xl">
        <h2 class="text-2xl font-bold mb-4">Java版 (PC)</h2>
        <ol class="list-decimal list-inside text-gray-200 mb-4">
          <li>Minecraft Java版を起動</li>
          <li>「マルチプレイ」を選択</li>
          <li>「サーバーを追加」をクリック</li>
          <li>サーバーアドレスに <span class="font-mono text-green-400">mc.example.com</span> を入力</li>
          <li>サーバーに参加！</li>
        </ol>
        <img src="/images/java-sample.png" alt="Java版サンプル" class="rounded-lg border border-gray-600">
      </section>

      <!-- 統合版 -->
      <section class="bg-gray-800 rounded-xl shadow-lg p-6 mb-8 max-w-2xl">
        <h2 class="text-2xl font-bold mb-4">統合版 (スマホ / Switch / Xbox)</h2>
        <ol class="list-decimal list-inside text-gray-200 mb-4">
          <li>Minecraftを起動</li>
          <li>「遊ぶ」 → 「サーバー」 → 「サーバー追加」を選択</li>
          <li>サーバーアドレスに <span class="font-mono text-green-400">bedrock.example.com</span></li>
          <li>ポート番号を <span class="font-mono text-green-400">19132</span> に設定</li>
          <li>保存して接続！</li>
        </ol>
        <img src="/images/bedrock-sample.png" alt="統合版サンプル" class="rounded-lg border border-gray-600">
      </section>

      <footer class="mt-12 text-gray-400 text-sm">© 2025 はらみサーバー</footer>
    </body>
    </html>
