apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-server.conf: |
    server {
        listen 80;
        server_name _;

        # /bluemap/s1 に末尾スラッシュがない場合はリダイレクト
        location = /bluemap/s1 {
            return 301 /bluemap/s1/;
        }

        # BlueMap s1 用リバースプロキシ
        location /bluemap/s1/ {
            proxy_pass http://mc-s1-mc-s1map-service.mc-haramis.svc.cluster.local:8100/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            # WebSocket 対応
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
