apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Haramis Server</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gray-900 text-white font-sans">
        <!-- Hero Section -->
        <section class="text-center py-12 px-4">
            <h1 class="text-4xl font-bold mb-4">ようこそ はら民限定マインクラフトサーバーへ</h1>
            <p class="text-lg text-gray-300 max-w-3xl mx-auto mb-8">
                本サイトは、配信者「はらみ」のサブスク限定マインクラフトサーバーの紹介サイトです。<br>
                以下のアイコンから各情報をご参照ください。
            </p>
        </section>

        <!-- Icon Navigation Section -->
        <section class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto px-4">
            <!-- Minecraftの入り方 -->
            <a href="#login" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/minecraft.png" alt="Minecraft" class="mb-4">
                <span class="text-xl font-semibold">マインクラフトの入り方</span>
            </a>

            <!-- サーバー内ルール -->
            <a href="#rules" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/rules.png" alt="Rules" class="mb-4">
                <span class="text-xl font-semibold">サーバー内のルール</span>
            </a>

            <!-- ワールドマップ -->
            <a href="/bluemap/s1/" target="_blank" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/map.png" alt="BlueMap" class="mb-4">
                <span class="text-xl font-semibold">ワールドマップ</span>
            </a>

            <!-- TikTok -->
            <a href="https://www.tiktok.com/@harami_tiktok" target="_blank" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/tiktok.png" alt="TikTok" class="mb-4">
                <span class="text-xl font-semibold">はらみ TikTok</span>
            </a>

            <!-- X -->
            <a href="https://x.com/harami_x" target="_blank" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/twitter.png" alt="X" class="mb-4">
                <span class="text-xl font-semibold">はらみ X</span>
            </a>

            <!-- lit.link -->
            <a href="https://lit.link/harami" target="_blank" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/link.png" alt="lit.link" class="mb-4">
                <span class="text-xl font-semibold">lit.link</span>
            </a>

            <!-- Discord -->
            <a href="https://discord.gg/XXXXX" target="_blank" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/discord-logo.png" alt="Discord" class="mb-4">
                <span class="text-xl font-semibold">サブスク限定Discord鯖</span>
            </a>

            <!-- Amazon欲しい物リスト -->
            <a href="https://www.amazon.co.jp/hz/wishlist/ls/XXXXXXXXX" target="_blank" class="bg-gray-800 hover:bg-gray-700 rounded-lg p-6 flex flex-col items-center shadow-md">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/amazon.png" alt="Amazon Wishlist" class="mb-4">
                <span class="text-xl font-semibold">Amazonほしい物リスト</span>
            </a>
        </section>

        <!-- Footer -->
        <footer class="bg-gray-800 text-center py-6 mt-12">
            <p>&copy; 2025 Haramis Server</p>
        </footer>
    </body>
    </html>
