apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Haramis Server</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gray-900 text-white font-sans">
        <!-- Header -->
        <header class="bg-gray-800 shadow-md">
            <div class="max-w-6xl mx-auto flex justify-between items-center p-4">
                <h1 class="text-2xl font-bold">Haramis Server</h1>
                <nav>
                    <ul class="flex space-x-6">
                        <li><a href="/master" class="hover:text-yellow-400">ログイン方法</a></li>
                        <li><a href="#bluemap" class="hover:text-yellow-400">BlueMap</a></li>
                        <li><a href="#streamer" class="hover:text-yellow-400">配信者リンク</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <!-- Hero Section -->
        <section class="text-center py-16">
            <h2 class="text-4xl font-bold mb-4">Minecraft サーバーへようこそ！</h2>
            <p class="text-lg text-gray-300">楽しいサバイバルと冒険が待っています。</p>
        </section>

        <!-- Login Section -->
        <section id="login" class="max-w-4xl mx-auto py-12 px-4">
            <h3 class="text-3xl font-semibold mb-6 text-yellow-400">ログイン方法</h3>
            <p class="mb-4">Discordに参加して、ロールを取得してください。</p>
            <a href="https://discord.gg/XXXXX" target="_blank" class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg text-lg font-bold">
                Discordに参加する
            </a>
        </section>

        <!-- BlueMap Section -->
        <section id="bluemap" class="max-w-4xl mx-auto py-12 px-4">
            <h3 class="text-3xl font-semibold mb-6 text-green-400">BlueMap</h3>
            <p class="mb-4">サーバーのワールドをブラウザで見てみよう！</p>
            <a href="/bluemap/s1/" target="_blank" class="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg text-lg font-bold">
                s1 マップを見る
            </a>
        </section>

        <!-- Streamer Links -->
        <section id="streamer" class="max-w-4xl mx-auto py-12 px-4">
            <h3 class="text-3xl font-semibold mb-6 text-pink-400">配信者リンク</h3>
            <div class="flex flex-col space-y-4">
                <a href="https://www.tiktok.com/@streamer" target="_blank" class="bg-pink-600 hover:bg-pink-700 text-white px-6 py-3 rounded-lg text-lg font-bold">
                    TikTokで見る
                </a>
                <a href="https://streamer.link" target="_blank" class="bg-purple-600 hover:bg-purple-700 text-white px-6 py-3 rounded-lg text-lg font-bold">
                    配信者リンク集 (.link)
                </a>
            </div>
        </section>

        <!-- Footer -->
        <footer class="bg-gray-800 text-center py-6 mt-12">
            <p>&copy; 2025 Haramis Server</p>
            <p>
                <a href="https://github.com/your-github" target="_blank" class="text-blue-400 hover:underline">GitHub</a>
            </p>
        </footer>
    </body>
    </html>
