apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-config.conf: |
    server {
        listen 80;
        server_name _;

        # BlueMap for s1
        location /bluemap/s1/ {
            proxy_pass http://mc-s1-mc-s1map-service.mc-haramis.svc.cluster.local:8100/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
