apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml

patches:
  - target:
      kind: Deployment
      name: mc-proxy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1024Mi
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: 1024m
  - path: service-LoadBalancer.yaml
