{
 "title": "Minecraft Network",
 "tags": [ "bungeecord" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": {
     "query": "label_values(bungeecord_managed_servers, proxy_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (server) (bungeecord_online_player{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Events per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bungeecord_player_chats_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "chats"
    },
    {
     "expr": "increase(bungeecord_server_list_pings_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "server list pings"
    },
    {
     "expr": "increase(bungeecord_player_connects_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "connects"
    },
    {
     "expr": "increase(bungeecord_player_kicks_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "kicks"
    },
    {
     "expr": "increase(bungeecord_player_disconnects_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (bungeecord_jvm_memory{type='used',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} used"
    },
    {
     "expr": "sum by (type) (bungeecord_jvm_memory{type='free',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} free"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_threads_current{proxy_name=~\"$proxy\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum by (state) (bungeecord_jvm_threads_state{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$proxy RAM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_memory{type='allocated', proxy_name=~\"$proxy\"}) - scalar(sum(bungeecord_jvm_memory{type='free', proxy_name=~\"$proxy\"}))"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(bungeecord_jvm_memory{proxy_name=~\".*\"}) by (proxy_name))"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_managed_servers{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_installed_network_plugins{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_online_player{proxy_name=~\"$proxy\"})",
     "legendFormat": "Online Player"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_max(avg(bungeecord_online_player_latency > 0),1000)",
     "legendFormat": "average player ping"
    }
   ]
  },
  {
   "title": "Online Player List",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 15 },
   "targets": [
    { "expr": "bungeecord_online_player > 0", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}