{
 "title": "ix-3110-SNMP-status",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "電源ユニット状態(0系)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoPowerSupplyStatus{picoPowerSupplyIndex=\"1\",target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "電源ユニット状態(1系)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoPowerSupplyStatus{picoPowerSupplyIndex=\"2\",target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "電圧",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoVoltage{target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "FAN状態",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoFanStatus{target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "FAN回転数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoFanRpm{target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoSchedRtUtl1Min{target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "メモリ使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoHeapUtil{target=\"ix-rt-ext\"}"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "picoCelsius{target=\"ix-rt-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "Portステータス",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-rt-general\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-rt-ext\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{target=\"ix-rt-ext\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{target=\"ix-rt-ext\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{target=\"ix-rt-ext\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-rt-general\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-rt-general\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "picoSchedRtUtl1Sec{target=\"ix-rt-ext\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "メモリ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "picoHeapSize{target=\"ix-rt-ext\"}",
     "legendFormat": "MAX"
    },
    {
     "expr": "picoHeapUtil{target=\"ix-rt-ext\"} / 100 * picoHeapSize{target=\"ix-rt-ext\"}",
     "legendFormat": "USE"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-rt-general\"}[5m])",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-rt-general\"}[5m])",
     "legendFormat": "In: {{ifName}}"
    }
   ]
  }
 ]
}