{
 "title": "Minecraft Network",
 "tags": [ "bungeecord" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": {
     "query": "label_values(bungeecord_managed_servers,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod, server) (bungeecord_online_players{pod=~\"$proxy\"})",
     "legendFormat": "{{server}}({{pod}})"
    }
   ]
  },
  {
   "title": "Events per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bungeecord_player_chats_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "chats ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_server_list_pings_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "server list pings ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_player_connects_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "connects ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_player_kicks_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "kicks ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_player_disconnects_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "disconnects ({{pod}})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(type, pod) (bungeecord_jvm_memory{type=\"used\", pod=~\"$proxy\"})",
     "legendFormat": "{{server}} used({{pod}})"
    },
    {
     "expr": "sum by(type, pod) (bungeecord_jvm_memory{type=\"free\", pod=~\"$proxy\"})",
     "legendFormat": "{{server}} free({{pod}})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (bungeecord_jvm_threads_current{pod=~\"$proxy\"})",
     "legendFormat": "TOTAL ({{pod}})"
    },
    {
     "expr": "sum by(state, pod) (bungeecord_jvm_threads_state{pod=~\"$proxy\"})",
     "legendFormat": "{{state}} ({{pod}})"
    }
   ]
  },
  {
   "title": "$proxy RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 12 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_memory{type='allocated', pod=~\"$proxy\"}) - scalar(sum(bungeecord_jvm_memory{type='free', pod=~\"$proxy\"}))"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_managed_servers{pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (bungeecord_server_list_pings_total{pod=~\"$proxy\"})",
     "legendFormat": "average player ping ({{pod}})"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_installed_network_plugins{pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_online_players{pod=~\"$proxy\"})",
     "legendFormat": "Online Players"
    }
   ]
  },
  {
   "title": "Online Player List",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 15 },
   "targets": [
    { "expr": "bungeecord_online_players > 0", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(bungeecord_jvm_memory{pod=~\".*\"}) by (pod))"
    }
   ]
  }
 ]
}