{
 "title": "Minecraft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": "label_values(mc_players_total, server_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_players_total{server_name=~\"$server_name\"}",
     "legendFormat": "Unique ({{server_name}})"
    },
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=~\"$server_name\"})",
     "legendFormat": "Online ({{world}}) ({{server_name}})"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{server_name=~\"$server_name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type=~\"allocated\", server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(server_name) (mc_loaded_chunks_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}} ({{server_name}})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', server_name=~\"$server_name\"}",
     "legendFormat": "Allocated ({{server_name}})"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"} - scalar(mc_jvm_memory{type='free', server_name=~\"$server_name\"})",
     "legendFormat": "Used ({{server_name}})"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_entities_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}}_total ({{server_name}})"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "TPS ({{server_name}})"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(world, level, profession, server_name) (mc_villagers_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}}) ({{server_name}})"
    }
   ]
  }
 ]
}