apiVersion: v1
kind: Service
metadata:
  name: geyser-service
  labels:
    app: mc-proxy
spec:
  type: ClusterIP
  ports:
    - name: geyser-service
      port: 25565
      protocol: TCP
      targetPort: proxy-service
  selector:
    app: mc-proxy