apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanata-java-world-pv
  labels:
    app: kanata-java-world-pv
spec:
  storageClassName: "nfs-storage"
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/mc-kanata/s1/world