apiVersion: v1
kind: ConfigMap
metadata:
  name: ddnsnow-auth-hook
  namespace: mc-haramis
data:
  ddnsnow-auth-hook.sh: |
    #!/bin/bash
    # Kubernetes Secret から渡された環境変数を使用
    # CERTBOT_DOMAIN と CERTBOT_VALIDATION は cert-manager が設定
    wget -q -O /tmp/DDNSNow_acme.log "https://f5.si/update.php?domain=${CERTBOT_DOMAIN}&password=${DDNSNOW_API_TOKEN}&acme=${CERTBOT_VALIDATION}"
    sleep 65
