apiVersion: batch/v1
kind: Job
metadata:
  name: ddnsnow-webhook
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: webhook
        image: alpine:3.18
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache wget
            cp /scripts/ddnsnow-auth-hook.sh /tmp/ddnsnow-auth-hook.sh
            chmod +x /tmp/ddnsnow-auth-hook.sh
            /tmp/ddnsnow-auth-hook.sh
        env:
          - name: DDNSNOW_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: ddns-now-secret
                key: API_TOKEN
          - name: CERTBOT_DOMAIN
            value: "test.haramiverse.f5.si"  # cert-manager が本番時に上書き
          - name: CERTBOT_VALIDATION
            value: "dummy"  # cert-manager が本番時に上書き
        volumeMounts:
          - name: script
            mountPath: /scripts
            readOnly: true
      volumes:
        - name: script
          configMap:
            name: ddnsnow-auth-hook
            items:
              - key: ddnsnow-auth-hook.sh
                path: ddnsnow-auth-hook.sh
