apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: $2y$10$mqhcbzPnSWTukQc2n.uUvecI9Tk0BFjeaPcdpBeFpnzTnq/wjQYuW
  admin.passwordMtime: "2026-04-18T00:00:00Z"