apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
  annotations:
    configmap.reloader.stakater.com/reload: "nginx-html"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: nginx-links
              mountPath: /usr/share/nginx/html/links/links.json
              subPath: links.json
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-html
        - name: nginx-links
          configMap:
            name: nginx-links
