{
 "title": "Minecraft Network",
 "tags": [ "bungeecord" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "オンラインプレイヤー",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(server) (bungeecord_online_player)",
     "legendFormat": "{{server}}"
    },
    {}
   ]
  },
  {
   "title": "イベント数(1分あたり)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bungeecord_player_chats_total[1m])",
     "legendFormat": "chats"
    },
    {
     "expr": "increase(bungeecord_server_list_pings_total[1m])",
     "legendFormat": "server list pings"
    },
    {
     "expr": "increase(bungeecord_player_connects_total[1m])",
     "legendFormat": "connects"
    },
    {
     "expr": "increase(bungeecord_player_kicks_total[1m])",
     "legendFormat": "kicks"
    },
    {
     "expr": "increase(bungeecord_player_disconnects_total[1m])",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "JVM メモリ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(type) (bungeecord_jvm_memory{type=\"free\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum by(type) (bungeecord_jvm_memory{type=\"used\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "スレッド",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bungeecord_jvm_threads_current", "legendFormat": "TOTAL" },
    {
     "expr": "sum by(state) (bungeecord_jvm_threads_state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "メモリ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_memory{type='allocated'}) - scalar(sum(bungeecord_jvm_memory{type='free'}))"
    }
   ]
  },
  {
   "title": "プレイヤー数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bungeecord_online_player)", "legendFormat": "Online Players" }
   ]
  },
  {
   "title": "サーバー数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bungeecord_managed_servers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "運用プロキシ数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(bungeecord_jvm_memory{pod=~\".*\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_server_list_pings_total",
     "legendFormat": "average player ping"
    }
   ]
  },
  {
   "title": "Plugins数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_installed_network_plugins",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}