apiVersion: v1
kind: PersistentVolume
metadata:
  name: haramis-lobby-pv
  labels:
    app: haramis-lobby
spec:
  storageClassName: haramis-lobby-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/haramis-server/lobby/world/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haramis-lobby-pvc
  labels:
    app: haramis-lobby
spec:
  storageClassName: haramis-lobby-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
