apiVersion: v1
kind: Service
metadata:
  name: mc-service
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  ports:
  - name: mc-service
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: mc-cron
    port: 25575
    protocol: TCP
    targetPort: 25575
  selector:
    app: minecraft
  loadBalancerIP: 192.168.15.201
