apiVersion: v1
kind: PersistentVolume
metadata:
  name: haramis-lobby-backup-pv
  labels:
    app: haramis-lobby
spec:
  storageClassName: haramis-lobby-backup-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.140
    path: /usbssd/mic-backup/haramis-server/lobby/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haramis-lobby-backup-pvc
  labels:
    app: haramis-lobby
spec:
  storageClassName: haramis-lobby-backup-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
