apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: mc-lobby
spec:
  template:
    metadata:
      labels:
        app: mc-lobby
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/latest"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}"
      containers:
        - name: minecraft
          env:
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: SPAWN_ANIMALS
              value: "false"
            - name: SPAWN_MONSTERS
              value: "false"
            - name: SPAWN_NPCS
              value: "false"
            - name: CFG_ALLOW_END
              value: "false"
            # ------lobby用の変数設定 ------
            # ------LuckPermsのサーバー名 ------
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: lobby
            - name: CFG_LUCKPERMS_SQLSERVER_DATABASE
              value: haramis-server
            # ------music用コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ worldedit ------
            - name: init-download-volume
              mountPath: /data/plugins/worldedit.jar
              subPath: worldedit.jar
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-lobby-pvc
