apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/latest"
            - name: WORLDGUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/latest"
            - name: SERVERSPAWN_URL
              value: "https://dev.bukkit.org/projects/serverspawn-by-goodgamer123/files/latest"
            - name: HOLOGRAMS_URL
              value: "https://github.com/DecentSoftware-eu/DecentHolograms/releases/download/2.9.6/DecentHolograms-2.9.6.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/ServerSpawn.jar "${SERVERSPAWN_URL}" &&
              wget -O /root/initContainer-download/DecentHolograms.jar "${HOLOGRAMS_URL}"
      containers:
        - name: minecraft
          env:
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: SPAWN_ANIMALS
              value: "false"
            - name: SPAWN_MONSTERS
              value: "false"
            - name: SPAWN_NPCS
              value: "false"
            - name: CFG_ALLOW_END
              value: "false"
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: lobby
            - name: CFG_LUNACHAT_LANGUAGE
              value: ja
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            # ------時間天候無効化コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ worldedit ------
            - name: init-download-volume
              mountPath: /data/plugins/worldedit.jar
              subPath: worldedit.jar
            # ------ worldguard ------
            - name: init-download-volume
              mountPath: /data/plugins/worldguard.jar
              subPath: worldguard.jar
            # ------ ServerSpawn ------
            - name: init-download-volume
              mountPath: /data/plugins/ServerSpawn.jar
              subPath: ServerSpawn.jar
            # ------ DecentHolograms ------
            - name: init-download-volume
              mountPath: /data/plugins/DecentHolograms.jar
              subPath: DecentHolograms.jar
            # ------ holograms-S1_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-S1_Gateway.yml
              subPath: holograms-S1_Gateway.yml
            # ------ holograms-S2_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-S2_Gateway.yml
              subPath: holograms-S2_Gateway.yml
            # ------ holograms-music_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-S3-Gateway.yml
              subPath: holograms-S3-Gateway.yml
            # ------ serverspawn ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/ServerSpawn/ServerSpawn.yml
              subPath: ServerSpawn.yml
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-lobby-pvc
        # holograms-configmap格納先
        - name: mc-plugin-holograms-config
          configMap:
            name: mc-plugin-holograms-configs
        # serverspawn-configmap格納先
        - name: mc-plugin-serverspawn-config
          configMap:
            name: mc-plugin-serverspawn-config
