apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/manifests/apps/cluster-wide-apps/argocd
    repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox.git
    targetRevision: main
  syncPolicy:
    automated: {}
