apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-debug-server
spec:
  destination:
    namespace: debug
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/manifests/apps/overlays/mc-debug
    repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox.git
    targetRevision: main
  syncPolicy:
    automated: {}
