apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
            # letsencryptのキー
            - name: letsencrypt
              mountPath: /etc/letsencrypt
      volumes:
        - name: web-content
          configMap:
            name: web-content-config
        - name: letsencrypt
          persistentVolumeClaim:
            claimName: letsencrypt-pvc
