apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis-web
resources:
  # templates
  - ../../templates/nginx
  # config
  - ./config/web-content-config.yaml
  # pv&pvc
  - ./pv-letsencrypt.yaml
  - ./pv-ddnsnow.yaml
  # secret
  - ./http://nas.mcnet/k8s/mc-haramis/secret-ddnsnow-credentials.yaml


patches:
  - path: deployment.yaml
  - path: lb-service.yaml
  - path: config/nginx-conf.yaml
  - path: cron-job.yaml
