apiVersion: v1
kind: PersistentVolume
metadata:
  name: ddnsnow-pv
spec:
  storageClassName: ddnsnow-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/haramis-server/ddnsnow/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddnsnow-pvc
spec:
  storageClassName: ddnsnow-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
