apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-pv
spec:
  storageClassName: letsencrypt-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.6.140
    path: /usbssd/mic-backup/haramis-server/letsencrypt/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
