apiVersion: batch/v1
kind: CronJob
metadata:
  name: minecraft-frontend-restart-warning
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: notifier
              env:
                - name: RCON_HOST
                  value: mc-lobby-mc-service.mc-haramis.svc.cluster.local
