{
 "title": "CRS309-SNMP-status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "システム名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{target=\"crs309-general\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "ソフトウェア名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysDescr{target=\"crs309-general\"}",
     "legendFormat": "{{sysDescr}}"
    }
   ]
  },
  {
   "title": "起動時間",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{target=\"crs309-general\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "SFP温度",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalTemperature{target=\"crs309-ext\"})",
     "legendFormat": "SFP{{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "SFP電圧",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalSupplyVoltage{target=\"crs309-ext\"})",
     "legendFormat": "SFP {{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "バイアス電流",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalTxBiasCurrent{target=\"crs309-ext\"})",
     "legendFormat": "SFP{{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "SFP波長",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalWavelength{target=\"crs309-ext\"}) /100000000",
     "legendFormat": "SFP{{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "インターフェースサマリ",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{target=\"crs309-general\"}"
    },
    {
     "expr": "ifOperStatus{target=\"crs309-general\"}"
    },
    {
     "expr": "ifSpeed{target=\"crs309-general\"}"
    },
    {
     "expr": "ifMtu{target=\"crs309-general\"}"
    },
    {
     "expr": "ifType_info{target=\"crs309-general\"}"
    },
    {
     "expr": "ifAlias{target=\"crs309-general\"}"
    }
   ]
  },
  {
   "title": "送受信レートsummary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"crs309-general\"}[$__rate_interval])*8",
     "legendFormat": "送信-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\"}[$__rate_interval])*8",
     "legendFormat": "受信-{{ifName}}"
    }
   ]
  },
  {
   "title": "CPU温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mtxrHlProcessorTemperature{target=\"crs309-ext\"} /10",
     "legendFormat": "温度"
    }
   ]
  },
  {
   "title": "送受信レート \"MGMT\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"MGMT\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"MGMT\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート遷移(SFP)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    }
   ]
  },
  { "title": "送受信レート(SFP)詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "送受信レート \"SFP1\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP2\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP3\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP4\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP5\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP6\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP7\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP8\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "インターフェース詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "インターフェース\"SFP1\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 56 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP2\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP3\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP4\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP5\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP6\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP7\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP8\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  }
 ]
}