{
 "title": "ix-3110-SNMP-status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ソフトウェア名称",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysDescr{target=\"ix-3110-general\"}",
     "legendFormat": "{{sysDescr}}"
    }
   ]
  },
  {
   "title": "システム名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{target=\"ix-3110-general\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "起動時間",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{target=\"ix-3110-general\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "電源ユニット状態(0系)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoPowerSupplyStatus{picoPowerSupplyIndex=\"1\",target=\"ix-3110-ext\"}",
     "legendFormat": "0系"
    },
    {
     "expr": "picoPowerSupplyStatus{picoPowerSupplyIndex=\"2\",target=\"ix-3110-ext\"}",
     "legendFormat": "1系"
    }
   ]
  },
  {
   "title": "電圧",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoVoltage{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "FAN状態",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoFanStatus{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "FAN回転数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoFanRpm{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "送信レート",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet0\"}[5m])*8",
     "legendFormat": "GigaEthernet-0"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet1\"}[5m])*8",
     "legendFormat": "GigaEthernet-1"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet2\"}[5m])*8",
     "legendFormat": "GigaEthernet-2"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3\"}[5m])*8",
     "legendFormat": "GigaEthernet-3"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"BVI1\"}[5m])*8",
     "legendFormat": "LAN-bridge"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3.1-PPP\"}[5m])*8",
     "legendFormat": "WAN-PPPoE"
    }
   ]
  },
  {
   "title": "受信レート",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet0\"}[5m])*8",
     "legendFormat": "GigaEthernet-0"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet1\"}[5m])*8",
     "legendFormat": "GigaEthernet-1"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet2\"}[5m])*8",
     "legendFormat": "GigaEthernet-2"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3\"}[5m])*8",
     "legendFormat": "GigaEthernet-3"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"BVI1\"}[5m])*8",
     "legendFormat": "LAN-bridge"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3.1-PPP\"}[5m])*8",
     "legendFormat": "WAN-PPPoE"
    }
   ]
  },
  {
   "title": "メモリ使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoHeapUtil{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoSchedRtUtl1Min{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "picoCelsius{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "picoSchedRtUtl1Sec{target=\"ix-3110-ext\"}",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "メモリ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "picoHeapSize{target=\"ix-3110-ext\"}",
     "legendFormat": "最大"
    },
    {
     "expr": "picoHeapUtil{target=\"ix-3110-ext\"} / 100 * picoHeapSize{target=\"ix-3110-ext\"}",
     "legendFormat": "使用中"
    }
   ]
  },
  {
   "title": "送受信レート",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"BVI1\"}[$__rate_interval])*8",
     "legendFormat": "Out: LAN-bridge"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"BVI1\"}[$__rate_interval])*8",
     "legendFormat": "In: LAN-bridge"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3.1-PPP\"}[$__rate_interval])*8",
     "legendFormat": "Out: WAN-PPPoE"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3.1-PPP\"}[$__rate_interval])*8",
     "legendFormat": "In: WAN-PPPoE"
    }
   ]
  },
  { "title": "送受信レート詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "送受信レート \"GigaEthernet-0\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"GigaEthernet-1\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"GigaEthernet-2\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"GigaEthernet-3\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "インターフェース詳細",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true
  },
  {
   "title": "インターフェース\"GigaEthernet-0\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 51 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"GigaEthernet-1\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"GigaEthernet-2\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"GigaEthernet-3\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  }
 ]
}
{
 "title": "Minecraft Network",
 "tags": [ "bungeecord" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": {
     "query": "label_values(bungeecord_managed_servers,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "オンラインプレイヤー",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod, server) (bungeecord_online_players{pod=~\"$proxy\"})",
     "legendFormat": "{{server}}({{pod}})"
    }
   ]
  },
  {
   "title": "イベント数(1分あたり)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bungeecord_player_chats_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "chats ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_server_list_pings_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "server list pings ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_player_connects_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "connects ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_player_kicks_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "kicks ({{pod}})"
    },
    {
     "expr": "increase(bungeecord_player_disconnects_total{pod=~\"$proxy\"}[1m])",
     "legendFormat": "disconnects ({{pod}})"
    }
   ]
  },
  {
   "title": "JVM メモリ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(type, pod) (bungeecord_jvm_memory{type=\"used\", pod=~\"$proxy\"})",
     "legendFormat": "{{server}} used({{pod}})"
    },
    {
     "expr": "sum by(type, pod) (bungeecord_jvm_memory{type=\"free\", pod=~\"$proxy\"})",
     "legendFormat": "{{server}} free({{pod}})"
    }
   ]
  },
  {
   "title": "スレッド",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (bungeecord_jvm_threads_current{pod=~\"$proxy\"})",
     "legendFormat": "TOTAL ({{pod}})"
    },
    {
     "expr": "sum by(state, pod) (bungeecord_jvm_threads_state{pod=~\"$proxy\"})",
     "legendFormat": "{{state}} ({{pod}})"
    }
   ]
  },
  {
   "title": "$proxy メモリ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_memory{type='allocated', pod=~\"$proxy\"}) - scalar(sum(bungeecord_jvm_memory{type='free', pod=~\"$proxy\"}))"
    }
   ]
  },
  {
   "title": "サーバー数",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_managed_servers{pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Plugins数",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_installed_network_plugins{pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (bungeecord_server_list_pings_total{pod=~\"$proxy\"})",
     "legendFormat": "average player ping ({{pod}})"
    }
   ]
  },
  {
   "title": "プレイヤー数",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_online_players{pod=~\"$proxy\"})",
     "legendFormat": "Online Players"
    }
   ]
  },
  {
   "title": "運用プロキシ数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(bungeecord_jvm_memory{pod=~\".*\"}) by (pod))"
    }
   ]
  }
 ]
}
{
 "title": "MinecraftServer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": {
     "query": "label_values(mc_players_total,server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "プレイヤーオンライン数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{server_name=~\"$server_name\"})"
    }
   ]
  },
  {
   "title": "プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "mc_players_total{server_name=~\"$server_name\"}",
     "legendFormat": "総人口 ({{server_name}})"
    },
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=~\"$server_name\"})",
     "legendFormat": "オンライン数 ({{world}}) ({{server_name}})"
    }
   ]
  },
  {
   "title": "JVMメモリ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type=~\"allocated\", server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', server_name=~\"$server_name\"}",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"} - scalar(mc_jvm_memory{type='free', server_name=~\"$server_name\"})",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"}",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "TPS ({{server_name}})"
    }
   ]
  },
  {
   "title": "Tickレート遷移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "TPS ({{server_name}})"
    }
   ]
  },
  {
   "title": "読み込みチャンク数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count by(world, server_name) (mc_loaded_chunks_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}} ({{server_name}})"
    }
   ]
  },
  {
   "title": "エンティティ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_entities_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}}_total ({{server_name}})"
    }
   ]
  },
  {
   "title": "villagers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(world, level, profession, server_name) (mc_villagers_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}}) ({{server_name}})"
    }
   ]
  }
 ]
}
{
 "title": "CRS309-SNMP-status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "システム名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{target=\"crs309-general\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "ソフトウェア名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysDescr{target=\"crs309-general\"}",
     "legendFormat": "{{sysDescr}}"
    }
   ]
  },
  {
   "title": "起動時間",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{target=\"crs309-general\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "SFP温度",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalTemperature{target=\"crs309-ext\"})",
     "legendFormat": "SFP{{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "SFP電圧",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalSupplyVoltage{target=\"crs309-ext\"})",
     "legendFormat": "SFP {{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "バイアス電流",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalTxBiasCurrent{target=\"crs309-ext\"})",
     "legendFormat": "SFP{{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "SFP波長",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mtxrOpticalIndex) (mtxrOpticalWavelength{target=\"crs309-ext\"}) /100000000",
     "legendFormat": "SFP{{mtxrOpticalIndex}}"
    }
   ]
  },
  {
   "title": "インターフェースサマリ",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{target=\"crs309-general\"}"
    },
    {
     "expr": "ifOperStatus{target=\"crs309-general\"}"
    },
    {
     "expr": "ifSpeed{target=\"crs309-general\"}"
    },
    {
     "expr": "ifMtu{target=\"crs309-general\"}"
    },
    {
     "expr": "ifType_info{target=\"crs309-general\"}"
    },
    {
     "expr": "ifAlias{target=\"crs309-general\"}"
    }
   ]
  },
  {
   "title": "送受信レートsummary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"crs309-general\"}[$__rate_interval])*8",
     "legendFormat": "送信-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\"}[$__rate_interval])*8",
     "legendFormat": "受信-{{ifName}}"
    }
   ]
  },
  {
   "title": "CPU温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mtxrHlProcessorTemperature{target=\"crs309-ext\"} /10",
     "legendFormat": "温度"
    }
   ]
  },
  {
   "title": "送受信レート \"MGMT\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"MGMT\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"MGMT\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート遷移(SFP)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    }
   ]
  },
  { "title": "送受信レート(SFP)詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "送受信レート \"SFP1\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP2\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP3\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP4\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP5\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP6\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP7\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"SFP8\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "インターフェース詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "インターフェース\"SFP1\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 56 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP1\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP2\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP2\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP3\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP3\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP4\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP4\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP5\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP5\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP6\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP6\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP7\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP7\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"SFP8\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"crs309-general\", ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"crs309-general\",ifName=\"SFP8\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  }
 ]
}