{
 "title": "x230-10GP-SNMP-Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "システム名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{target=\"x230\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "ソフトウェア名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysDescr{target=\"x230\"}",
     "legendFormat": "{{sysDescr}}"
    }
   ]
  },
  {
   "title": "起動時間",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{target=\"x230\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "インターフェースサマリ",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{target=\"x230\"}"
    },
    {
     "expr": "ifOperStatus{target=\"x230\"}"
    },
    {
     "expr": "ifSpeed{target=\"x230\"}"
    },
    {
     "expr": "ifMtu{target=\"x230\"}"
    },
    {
     "expr": "ifType_info{target=\"x230\"}"
    },
    {
     "expr": "ifAlias{target=\"x230\"}"
    }
   ]
  },
  {
   "title": "送受信レートsummary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"x230\",ifName=~\"port1\\\\.0\\\\.([1-9])\"}[$__rate_interval])*8",
     "legendFormat": "送信-{{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"x230\",ifName=~\"port1\\\\.0\\\\.(1[0-9])\"}[$__rate_interval])*8",
     "legendFormat": "送信-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=~\"port1\\\\.0\\\\.([1-9])\"}[$__rate_interval])*8",
     "legendFormat": "受信-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=~\"port1\\\\.0\\\\.(1[0-9])\"}[$__rate_interval])*8",
     "legendFormat": "受信-{{ifName}}"
    }
   ]
  },
  {
   "title": "送受信レート遷移",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=~\"port1\\\\.0\\\\.([1-9]||1[0-9]||2[0-9])\"}[$__rate_interval])*8",
     "legendFormat": "Out-{{ifName}}"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=~\"port1\\\\.0\\\\.([1-9]||1[0-9]||2[0-9])\"}[$__rate_interval])*8",
     "legendFormat": "In-{{ifName}}"
    }
   ]
  },
  { "title": "送受信レート詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.1\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.2\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.3\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.4\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.5\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.6\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.7\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-1.0.8\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-SFP-1.0.9\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"Gigabit-Ethernet-SFP-1.0.10\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "インターフェース詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.1\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 64 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.1\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.2\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.2\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.3\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.3\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.4\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.4\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.5\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.5\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.6\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.6\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.7\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.7\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-1.0.8\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.8\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-SFP-1.0.9\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.9\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"Gigabit-Ethernet-SFP-1.0.10\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"x230\",ifName=\"port1.0.10\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  }
 ]
}