{
 "title": "ix-3110-SNMP-status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ソフトウェア名称",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysDescr{target=\"ix-3110-general\"}",
     "legendFormat": "{{sysDescr}}"
    }
   ]
  },
  {
   "title": "システム名称",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{target=\"ix-3110-general\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "起動時間",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{target=\"ix-3110-general\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "電源ユニット状態(0系)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoPowerSupplyStatus{picoPowerSupplyIndex=\"1\",target=\"ix-3110-ext\"}",
     "legendFormat": "0系"
    },
    {
     "expr": "picoPowerSupplyStatus{picoPowerSupplyIndex=\"2\",target=\"ix-3110-ext\"}",
     "legendFormat": "1系"
    }
   ]
  },
  {
   "title": "電圧",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoVoltage{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "FAN状態",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoFanStatus{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "FAN回転数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoFanRpm{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "送信レート",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet0\"}[5m])*8",
     "legendFormat": "GigaEthernet-0"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet1\"}[5m])*8",
     "legendFormat": "GigaEthernet-1"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet2\"}[5m])*8",
     "legendFormat": "GigaEthernet-2"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3\"}[5m])*8",
     "legendFormat": "GigaEthernet-3"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"BVI1\"}[5m])*8",
     "legendFormat": "LAN-bridge"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3.1-PPP\"}[5m])*8",
     "legendFormat": "WAN-PPPoE"
    }
   ]
  },
  {
   "title": "受信レート",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet0\"}[5m])*8",
     "legendFormat": "GigaEthernet-0"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet1\"}[5m])*8",
     "legendFormat": "GigaEthernet-1"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet2\"}[5m])*8",
     "legendFormat": "GigaEthernet-2"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3\"}[5m])*8",
     "legendFormat": "GigaEthernet-3"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"BVI1\"}[5m])*8",
     "legendFormat": "LAN-bridge"
    },
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifDescr=\"GigaEthernet3.1-PPP\"}[5m])*8",
     "legendFormat": "WAN-PPPoE"
    }
   ]
  },
  {
   "title": "メモリ使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoHeapUtil{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "picoSchedRtUtl1Min{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "picoCelsius{target=\"ix-3110-ext\"}",
     "legendFormat": "IX-3110"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "picoSchedRtUtl1Sec{target=\"ix-3110-ext\"}",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "メモリ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "picoHeapSize{target=\"ix-3110-ext\"}",
     "legendFormat": "最大"
    },
    {
     "expr": "picoHeapUtil{target=\"ix-3110-ext\"} / 100 * picoHeapSize{target=\"ix-3110-ext\"}",
     "legendFormat": "使用中"
    }
   ]
  },
  {
   "title": "送受信レート",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"BVI1\"}[$__rate_interval])*8",
     "legendFormat": "Out: LAN-bridge"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"BVI1\"}[$__rate_interval])*8",
     "legendFormat": "In: LAN-bridge"
    },
    {
     "expr": "irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3.1-PPP\"}[$__rate_interval])*8",
     "legendFormat": "Out: WAN-PPPoE"
    },
    {
     "expr": "-irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3.1-PPP\"}[$__rate_interval])*8",
     "legendFormat": "In: WAN-PPPoE"
    }
   ]
  },
  { "title": "送受信レート詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "送受信レート \"GigaEthernet-0\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"GigaEthernet-1\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"GigaEthernet-2\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "送受信レート \"GigaEthernet-3\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifHCOutOctets{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "インターフェース詳細",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true
  },
  {
   "title": "インターフェース\"GigaEthernet-0\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 51 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet0\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"GigaEthernet-1\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet1\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"GigaEthernet-2\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet2\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "インターフェース\"GigaEthernet-3\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{target=\"ix-3110-general\",ifName=\"GigaEthernet3\"}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  }
 ]
}