{
 "title": "MinecraftServer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": {
     "query": "label_values(mc_players_total,server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "プレイヤーオンライン数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{server_name=~\"$server_name\"})"
    }
   ]
  },
  {
   "title": "プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "mc_players_total{server_name=~\"$server_name\"}",
     "legendFormat": "総人口 ({{server_name}})"
    },
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=~\"$server_name\"})",
     "legendFormat": "オンライン数 ({{world}}) ({{server_name}})"
    }
   ]
  },
  {
   "title": "JVMメモリ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type=~\"allocated\", server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', server_name=~\"$server_name\"}",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"} - scalar(mc_jvm_memory{type='free', server_name=~\"$server_name\"})",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"}",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "TPS ({{server_name}})"
    }
   ]
  },
  {
   "title": "Tickレート遷移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "TPS ({{server_name}})"
    }
   ]
  },
  {
   "title": "読み込みチャンク数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count by(world, server_name) (mc_loaded_chunks_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}} ({{server_name}})"
    }
   ]
  },
  {
   "title": "エンティティ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_entities_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}}_total ({{server_name}})"
    }
   ]
  },
  {
   "title": "villagers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(world, level, profession, server_name) (mc_villagers_total{server_name=~\"$server_name\"})",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}}) ({{server_name}})"
    }
   ]
  }
 ]
}