apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: mc-s1-
resources:
  # template
  - ../../templates/minecraft-server
  # service
  - svc-LoadBalancer-s1map.yaml
  # pv & pvc
  - ./pv-haramis-s1-world.yaml
  - ./pv-haramis-s1-backup.yaml.yaml
  # secret
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-common.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-s1.yaml
  # config
  - ./config/mc-plugin-bluemap-worlds-config.yaml
patches:
  - path: statefulset-haramis.yaml
  - path: cronjob/frontend-restart-warning-s1.yaml
