apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: mc-s1-
resources:
  # template
  - ../../templates/minecraft-server
  # pv & pvc
  - ./pv-haramis-s1.yaml
  # secret
  - http://nas.mcnet/k8s/secret-haramis.yaml
  
  # config

patches:
  - target:
      kind: StatefulSet
      name: minecraft
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/27/valueFrom/secretKeyRef/key
        value: CFG_DISCORD_SRV_LOG_S1_CHANNEL_KEY
      - op: replace
        path: /spec/template/spec/containers/0/env/28/valueFrom/secretKeyRef/key
        value: CFG_DISCORD_SRV_CONSOLE_S1_CHANNEL_KEY
  - path: statefulset-haramis.yaml
  - path: cronjob/frontend-restart-warning-s1.yaml
