apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: mc-s1-
resources:
  # template
  - ../../templates/minecraft-server
  # pv & pvc

  # secret
  - http://nas.mcnet/k8s/secret-haramis.yaml
  
  # config

patches:
