apiVersion: v1
kind: Service
metadata:
  name: lb-bluemap
  labels:
    app: mc-map
spec:
  ports:
  - name: mc-map
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: minecraft
  type: LoadBalancer
  loadBalancerIP: 192.168.15.222
