apiVersion: v1
kind: Service
metadata:
  name: mc-s1rcon-service
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  ports:
  - name: mc-recon
    port: 25575
    protocol: TCP
    targetPort: 25575
  selector:
    app: minecraft
