apiVersion: v1
kind: PersistentVolume
metadata:
  name: haramis-s1-pv-iscsi
  labels:
    app: haramis-s1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.6.140:3260
    iqn: iqn.2004-04.com.qnap:ts-253d:iscsi.target-1.4bd441
    lun: 1
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haramis-s1-pvc
  labels:
    app: haramis-s1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: haramis-s1-pv-iscsi
