apiVersion: v1
kind: PersistentVolume
metadata:
  name: haramis-s1-pv
  labels:
    app: haramis-s1
spec:
  storageClassName: haramis-s1-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/haramis-server/s1/world/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haramis-s1-pvc
  labels:
    app: haramis-s1
spec:
  storageClassName: haramis-s1-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
