apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.37.0
          env:
            - name: INVENTORY_URL
              value: "https://www.spigotmc.org/resources/mysql-inventory-bridge.7849/download?version=357227"
            - name: ONEPLAYERSLEEP_URL
              value: "https://www.spigotmc.org/resources/one-player-sleep.31585/download?version=384206"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/MysqlInventoryBridge.jar "${INVENTORY_URL}" &&
              wget -O /root/initContainer-download/OnePlayerSleep.jar "${ONEPLAYERSLEEP_URL}"
      containers:
        - name: minecraft
          env:
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: s1
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 4G
            - name: CFG_DISCORD_SRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-s1-secret
                  key: CFG_DISCORD_SRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORD_SRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-s1-secret
                  key: CFG_DISCORD_SRV_CONSOLE_CHANNEL_KEY
            - name: CFG_CFG_DISCORDSRV_ROLE_AUTH
              value: "true"
            - name: CFG_DISCORDSRV_ADMIN_USER
              value: haramiten
          resources:
            requests:
              memory: 6G
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
              subPath: world
            - name: world-data
              mountPath: /data/world_nether
              subPath: world_nether
            - name: world-data
              mountPath: /data/the_end
              subPath: the_end
            # ------ world-backupデータ ------
            - name: world-data-backup
              mountPath: /data/Backups
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ inventory-bridge ------
            - name: init-download-volume
              mountPath: /data/plugins/MysqlInventoryBridge.jar
              subPath: MysqlInventoryBridge.jar
            # ------ OnePlayerSleep ------
            - name: init-download-volume
              mountPath: /data/plugins/OnePlayerSleep.jar
              subPath: OnePlayerSleep.jar
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-s1-pvc
        # world-backupデータの永続ストレージの指定
        - name: world-data-backup
          persistentVolumeClaim:
            claimName: haramis-s1-backup-pvc
