apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: INVENTORY_URL
              value: "https://www.spigotmc.org/resources/mysql-inventory-bridge.7849/download?version=357227"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/MysqlInventoryBridge.jar "${INVENTORY_URL}"
      containers:
        - name: minecraft
          env:
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: s1
            - name: CFG_LUNACHAT_LANGUAGE
              value: ja
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ inventory-bridge ------
            - name: init-download-volume
              mountPath: /data/plugins/MysqlInventoryBridge.jar
              subPath: MysqlInventoryBridge.jar
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-s1-pvc
