apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.37.0
          env:
            - name: BLUEMAP_URL
              value: "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.13/bluemap-5.13-paper.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/bluemap-paper.jar "${BLUEMAP_URL}"
      containers:
        - name: minecraft
          resources:
            requests:
              cpu: "4"
              memory: 6G
          env:
            # ---- 基本設定 ---- 
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 6G
            # ---- discord SRV ---- 
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: CFG_CFG_DISCORDSRV_ROLE_AUTH
              value: "true"
            - name: CFG_DISCORDSRV_ADMIN_USER
              value: haramiten
            - name: CFG_DISCORDSRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-s1
                  key: CFG_DISCORDSRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-s1
                  key: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
            # ---- luckperms ---- 
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: s1
            # --- spiget No ---
            # --- 31585：One Player Sleep
            # --- 7849：MySQL Inventory Bridge
            - name: SPIGET_RESOURCES
              value: "31585"
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
              subPath: world
            - name: world-data
              mountPath: /data/world_nether
              subPath: world_nether
            - name: world-data
              mountPath: /data/the_end
              subPath: the_end
            # ------ world-backupデータ ------
            - name: world-data-backup
              mountPath: /data/Backups
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ bluemap-paper ------
            - name: init-download-volume
              mountPath: /data/plugins/bluemap-paper.jar
              subPath: bluemap-paper.jar
            # ------plugins関連のマウント ------
            # ------ bluemap-world ------
            # worldのマウント
            - name: mc-plugin-bluemap-config
              mountPath: /config/plugins/BlueMap/maps/s1-world.conf
              subPath: bluemap-world.conf
            # world_netherのマウント
            - name: mc-plugin-bluemap-config
              mountPath: /config/plugins/BlueMap/maps/s1-world_nether.conf
              subPath: bluemap-world_nether.conf
            # world_the_endのマウント
            - name: mc-plugin-bluemap-config
              mountPath: /config/plugins/BlueMap/maps/s1-world_the_end.conf
              subPath: bluemap-world_the_end.conf
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-s1-pvc
        # world-backupデータの永続ストレージの指定
        - name: world-data-backup
          persistentVolumeClaim:
            claimName: haramis-s1-backup-pvc
        # bluemap-worldデータの永続ストレージの指定
        - name: mc-plugin-bluemap-config
          configMap:
            name: mc-plugin-bluemap-config
