apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-iscsi
provisioner: csi.trident.qnap.io
parameters:
  backendType: "qnap-iscsi"
  selector: "Performance=performance1"
  fsType: "ext4"
allowVolumeExpansion: true
