apiVersion: batch/v1
kind: Job
metadata:
  name: init-secret
  namespace: mc-haramis
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: generator
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret velocity-forwarding-secret -n mc-haramis >/dev/null 2>&1; then
                KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
                kubectl create secret generic velocity-forwarding-secret \
                  --from-literal=forwarding.secret=$KEY \
                  -n mc-haramis
              else
                echo "Secret already exists."
