apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
resources:
  # template
  - ../../templates/minecraft-proxy
  # velocity-config
  - ./velocity-common-config.yaml
  # plugin-config
  - ./velocity-plugin-config.yaml

patches:
  - target:
      kind: Deployment
      name: mc-proxy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1024Mi
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: 1024m
  - path: svc-LoadBalancer.yaml
