apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: haramis-
resources:
  # base
  - ../../base/minecraft-proxy
patches:
  - path: svc-LoadBalancer.yaml
  - path: velocity-common-haramis-config.yaml
  - path: velocity-plugin-minimotd-haramis-config.yaml
  - path: deployment-haramis.yaml
