apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: haramis-
resources:
  # templates
  - ../../templates/minecraft-proxy
  # secret
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-common.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-lobby.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-s1.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-s2.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-s3.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-haramis-exp-disney.yaml
patches:
  - path: svc-LoadBalancer.yaml
  - path: deployment-haramis.yaml
  - path: config/velocity-plugin-minimotd-haramis-config.yaml
