apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
resources:
  # template
  - ../../templates/minecraft-proxy
  # velocity-config
  - ./velocity-common-config.yaml
  # plugin-config
  - ./velocity-plugin-config.yaml
  # service
  - ./svc-LoadBalancer.yaml

patches:
