apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: haramis-
resources:
  # templates
  - ../../templates/minecraft-proxy
  # secret
  - http://nas.mcnet/k8s/secret-haramis.yaml
patches:
  - path: svc-LoadBalancer.yaml
  - path: deployment-haramis.yaml
  - path: config/velocity-common-haramis-config.yaml
  - path: config/velocity-plugin-minimotd-haramis-config.yaml
