apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
namePrefix: haramis-
resources:
  # templates
  - ../../templates/minecraft-proxy
  # secret
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-common.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-db_address.yaml
patches:
  - path: lb-service.yaml
  - path: deployment-haramis.yaml
  - path: config/velocity-haramis-config.yaml
  - path: config/velocity-plugin-minimotd-haramis-config.yaml
