apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
resources:
  # template
  - ../../../../templates/minecraft-proxy
  # velocity-config
  #- ./velocity-config.yaml
  # plugin-config
  #- ./plugin-config.yaml

patches:
