apiVersion: v1
kind: ConfigMap
metadata:
  name: access-config
data:
  config.yml: |
    # =====================
    # TikTok settings
    # =====================
    tiktok:
      # TikTok Live streamer username (without @)
      user: tv_asahi_news

    # =====================
    # HTTP forward settings
    # =====================
    http:
      # HTTP endpoint to which events are forwarded
      endpoint: "http://localhost:8080/event"
      # Timeout for HTTP requests (in seconds)
      timeout: 5