apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deployment
  - ./deployment.yaml
  # service
  - ./svc-LoadBalancer.yaml
  # metrics-service
  - ./metrics-patch.yaml
  # jmx-exporter-config
  - ../../templates/common/jmx-exporter-config.yaml
