apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deployment
  - ./deployment.yaml
  # service
  - ./svc-LoadBalancer.yaml
  # metrics-service
  - ./metrics-patch.yaml
  # jmx-exporter-config
  - ../../templates/common/jmx-exporter-config.yaml

  # config関連
  - ../../templates/minecraft-proxy/velocity-config.yaml
  - ../../templates/minecraft-proxy/velocity-forwarding-config.yaml
  - ../../templates/minecraft-proxy/velocity-plugin-LuckPerms-config.yaml
  - ../../templates/minecraft-proxy/velocity-plugin-bungeecord-prometheusexporter-config.yaml
  - ../../templates/minecraft-proxy/velocity-plugin-floodgate-config.yaml
  - ../../templates/minecraft-proxy/velocity-plugin-geyser-config.yaml
  - ../../templates/minecraft-proxy/velocity-plugin-geyserskinmanager-bungeecord-config.yaml
  - ../../templates/minecraft-proxy/velocity-plugin-minimotd-config.yaml
