apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          env:
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: SPAWN_ANIMALS
              value: "false"
            - name: SPAWN_MONSTERS
              value: "false"
            - name: SPAWN_NPCS
              value: "false"
            - name: CFG_ALLOW_END
              value: "false"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 4G
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: s2
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: CFG_DISCORD_SRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-s2-secret
                  key: CFG_DISCORD_SRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORD_SRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-s2-secret
                  key: CFG_DISCORD_SRV_CONSOLE_CHANNEL_KEY
            - name: CFG_CFG_DISCORDSRV_ROLE_AUTH
              value: "true"
            - name: CFG_DISCORDSRV_ADMIN_USER
              value: haramiten
            # ------時間天候無効化コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
          resources:
            requests:
              cpu: "2"
              memory: 4G
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
              subPath: world
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-s2-pvc
