apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: INVENTORY_URL
              value: "https://www.spigotmc.org/resources/mysql-inventory-bridge.7849/download?version=357227"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/MysqlInventoryBridge.jar "${INVENTORY_URL}"
      containers:
        - name: minecraft
          env:
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: s2
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: CFG_DISCORD_SRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-s2-secret
                  key: CFG_DISCORD_SRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORD_SRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-s2-secret
                  key: CFG_DISCORD_SRV_CONSOLE_CHANNEL_KEY
            - name: RCON_CMDS_STARTUP #34
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
          resources:
            requests:
              memory: 4G
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------

            # ------ world-backupデータ ------

            # ------initでダウンロードしたプラグインをマウント ------
            # ------ inventory-bridge ------
            - name: init-download-volume
              mountPath: /data/plugins/MysqlInventoryBridge.jar
              subPath: MysqlInventoryBridge.jar
