apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-ddnsnow
spec:
  schedule: "0 3 * * *" # 毎日3時に実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: certbot
              image: certbot/certbot:latest
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "証明書を更新中..."
                  certbot certonly \
                    --server "${SERVER}" \
                    --manual \
                    --preferred-challenges dns \
                    --manual-auth-hook /root/.ddnsnow/DDNSNowAcmeAuthHook.sh \
                    -d "${DOMAIN}" \
                    --agree-tos -m "${EMAIL}" --non-interactive --quiet \
                    --config-dir /etc/letsencrypt \
                    --work-dir /var/lib/letsencrypt
                  echo "完了"
              env:
                - name: DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: ddnsnow-credentials
                      key: DOMAIN
                - name: EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ddnsnow-credentials
                      key: EMAIL
                - name: SERVER
                  valueFrom:
                    secretKeyRef:
                      name: ddnsnow-credentials
                      key: SERVER
              volumeMounts:
                - name: ddnsnow-hook
                  mountPath: /root/.ddnsnow
                - name: letsencrypt
                  mountPath: /etc/letsencrypt
                - name: certbot-work
                  mountPath: /var/lib/letsencrypt
          restartPolicy: OnFailure
          volumes:
            - name: ddnsnow-hook
              persistentVolumeClaim:
                claimName: ddnsnow-pvc
                    mode: 0755
            - name: letsencrypt
              persistentVolumeClaim:
                claimName: letsencrypt-pvc
            - name: certbot-work
              emptyDir: {}
