apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deployment
  - ./deployment.yaml
  # service
  - ./lb-service.yaml
  # config関連
  - ./config/nginx-conf.yaml
  - ./config/ddnsnow-hook-script-config.yaml
  # cronjob
  - ./cron-job-letsencrypt.yaml
