apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deployment
  - ./deployment.yaml
  # service
  - ./svc-LoadBalancer.yaml
  # config
  - ./config/nginx-html.yaml
  - ./config/nginx-html-links.yaml
  
  - ./certbot/cronJob.yaml
  - ./certbot/pvc-certbot.yaml
