apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.13.1
    chart: ingress-nginx
    helm:
      values: |
        controller:
          replicaCount: 1
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.15.65
            nodePorts:
              http: 30080
              https: 30443
          admissionWebhooks:
            enabled: false
          metrics:
            enabled: true
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          ingressClass: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
