apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haramis-palworld
resources:
  # templates
  - ../../templates/palworld
  - pv-worlds.yaml
patches:
  - path: lb-service.yaml
  - path: pvc-worlds.yaml
  - path: config/config.yaml