apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-plugin-bluemap-config
data:
  bluemap-core.conf: |
    ##                          ##
    ##         BlueMap          ##
    ##       Core-Config        ##
    ##                          ##
    
    # 下記の設定 (accept-download) を TRUE に変更することで、あなたは Mojang の EULA (https://account.mojang.com/documents/minecraft_eula) に同意したと見なされます。
    # また、Minecraft (Java Edition) のライセンスを所有していることを確認し、
    # BlueMap が Mojang のサーバー (https://piston-meta.mojang.com/) から Minecraft クライアントファイル（Minecraft のバージョンに応じたもの）をダウンロード・利用することに同意することになります。
    # このファイルには Mojang に帰属するリソースが含まれており、再配布したり、EULA に反する利用をしてはいけません。
    # BlueMap はこのファイルのリソースを使用して、マップの 3D モデルを生成し、それにテクスチャを適用します。（これがないと BlueMap は動作しません。）
    accept-download: false
    
    # BlueMap がランタイム中に必要とするデータファイルや、レンダリングの進捗を保存して後で再開できるようにするためのフォルダです。
    # デフォルトは "bluemap" です。
    data: "bluemap"
    
    # BlueMap がマップをレンダリングする際に使用するスレッド数を変更します。
    # 値を大きくするとレンダリング速度が改善しますが、ホストマシンのパフォーマンスに影響を与える可能性があります。
    # 常に使用可能なプロセッサコア数以下に設定してください。
    # 0 または負の値を指定した場合は、利用可能なプロセッサコア数からその値を引いた数が使用されます。
    # （例：6 コアで値を -2 に設定すると、4 つのレンダリングプロセスが動作します）
    # デフォルトは 1 です。
    render-thread-count: 1
    
    # BlueMap がサーバーやワールドのディレクトリから Mod リソースやデータパックを見つけて読み込むかどうかを制御します。
    # デフォルトは true です。
    scan-for-mod-resources: true
    
    # true にすると、BlueMap は非常に基本的な利用状況（使用中の実装タイプとバージョンのみ）を https://metrics.bluecolored.de/bluemap/ に送信する場合があります。
    # これにより開発者は BlueMap の基本的な利用状況を把握でき、開発を続けるモチベーションになります！できれば有効のままにしてください :)
    # 送信されるデータの例： {"implementation":"bukkit","version":"5.11","mcVersion":"?"}
    # デフォルトは true です。
    metrics: true
    
    # デバッグログ用の設定セクション
    log: {
      # デバッグログが書き込まれるファイルです。
      # コメントアウトするとデバッグログ出力は完全に無効になります。
      # Java の String フォーマット構文を使用して、時間を追加できます。参考：https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
      # デフォルトはログ出力なしです。
      file: "bluemap/logs/debug.log"
      #file: "bluemap/logs/debug_%1$tF_%1$tT.log"
    
      # ロガーが既存のファイルに追記するか、上書きするかを指定します。
      # デフォルトは false（上書き）です。
      append: false
    }
