apiVersion: v1
kind: ConfigMap
metadata:
  name: access-config
data:
  config.yml: |
    # =====================
    # TikTok settings
    # =====================
    tiktok:
      # TikTok Live streamer username (without @)
      user: .vtuber12

    # =====================
    # HTTP forward settings
    # =====================
    http:
      # HTTP endpoint to which events are forwarded
      endpoint: "http://tiktok-stream.mc-jm-kodamarei.svc.cluster.local:8080/event"
      # Timeout for HTTP requests (in seconds)
      timeout: 5