apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: haramis-web-cert
spec:
  secretName: haramis-web-tls
  dnsNames:
    - test.haramiverse.f5.si
  issuerRef:
    name: letsencrypt-web
    kind: Issuer
