apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-web
  namespace: web
spec:
  acme:
    solvers:
      - dns01:
          webhook:
            groupName: acme.ddns-now.haramiverse
            solverName: ddns-now
            config:
              apiTokenSecretRef:
                name: dns-api-secret
                key: API_TOKEN
