apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: palworld-server
  name: palworld-server-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
