apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palworld-server
spec:
  serviceName: palworld-server
  replicas: 1

  selector:
    matchLabels:
      app: palworld-server

  template:
    metadata:
      labels:
        app: palworld-server

    spec:
      terminationGracePeriodSeconds: 120

      containers:
        - name: palworld
          image: thijsvanloef/palworld-server-docker:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: game
              containerPort: 53167
              protocol: UDP

            - name: query
              containerPort: 27015
              protocol: UDP

          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-secrets
                  key: rconPassword

          envFrom:
            - configMapRef:
                name: palworld-cm

          volumeMounts:
            - name: datadir
              mountPath: /palworld

          resources:
            requests:
              cpu: "2"
              memory: 6Gi
            limits:
              cpu: "4"
              memory: 8Gi

      volumes:
        - name: world-data
          persistentVolumeClaim:
            claimName: palworld-server-data