apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qnap-iscsi-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/qnap-dev/QNAP-CSI-PlugIn'
    targetRevision: main
    path: Deploy/Trident
    helm:
      values: |-
        trident:
          namespace: trident
          # BackendConfig の設定例
          backends:
            - name: qts-iscsi-backend
              storageDriverName: qnap-iscsi
              backendName: qts
              networkInterfaces: []
              storage:
                - serviceLevel: pool1
                  labels:
                    performance: performance1
        storageClasses:
          - name: iscsi-storage
            provisioner: csi.trident.qnap.io
            parameters:
              selector: "performance=performance1"
              fsType: "ext4"
            allowVolumeExpansion: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
