apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qnap-csi-iscsi       # Argo CD 上でのアプリ名
  namespace: argocd           # Argo CD がインストールされている namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/qnap-dev/QNAP-CSI-PlugIn'
    targetRevision: v1.5.0
    path: Helm/trident
  destination:
    server: https://kubernetes.default.svc
    namespace: trident
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
