apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qnap-csi-iscsi       # Argo CD 上でのアプリ名
  namespace: argocd           # Argo CD がインストールされている namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/qnap-dev/QNAP-CSI-PlugIn'
    chart: Helm/trident
    targetRevision: HEAD
    helm:
      values: |-
        # ===============================
        # QNAP CSI Driver Backend 設定
        # ===============================
        trident:
          backend:
            name: qts-iscsi
            storageDriverName: qnap-iscsi
            storageAddress: 192.168.6.140       # NAS の iSCSI 接続 IP
            networkInterfaces: ["Adapter3"]    # NAS 上の iSCSI 用インターフェース
            storage:
              - serviceLevel: pool1             # Virtual Pool 名（任意）
                labels:
                  iqn: iqn.2004-04.com.qnap:ts-253d:iscsi.target-1.4bd441
                features:
                  tiering: Enable               # 必要に応じて
        # ===============================
        # StorageClass 設定
        # ===============================
        storageClass:
          name: iscsi-storage
          provisioner: csi.trident.qnap.io
          parameters:
            selector: "iqn=iqn.2004-04.com.qnap:ts-253d:iscsi.target-1.4bd441"
            fsType: ext4
          allowVolumeExpansion: true
        # ===============================
        # Pod 側リソース & アクセスモード
        # ===============================
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        accessModes: ReadWriteOnce              # iSCSI の場合は RWO
  destination:
    server: https://kubernetes.default.svc
    namespace: trident
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
