apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qnap-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/qnap-dev/QNAP-CSI-PlugIn/tree/main/Helm/trident'
    chart: trident
    targetRevision: 1.5.0
    helm:
      values: |-
        controller:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        node:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        storageClass:
          name: qnap-iscsi-sc
          provisionerName: csi.qnap.com
          reclaimPolicy: Retain
          defaultClass: true
          allowVolumeExpansion: true
          accessModes: [ "ReadWriteOnce" ]
        iscsi:
          targetPortal: 192.168.6.140:3260
          iqn: iqn.2004-04.com.qnap:ts253d.lun1
          lun: 1
          fsType: ext4
          chapUsername: iscsiuser
          chapPassword: your-secret-pass
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
