apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-uuidredirect-config
data:
  uuidredirect-config.json: |
    {
      "ebd6ed5c-7a32-49fd-b287-df57f2ffb33b": {
        "username": "maron_12345",
        "server": "jamming"
      },
      "cc0d7d56-8a2a-49b7-b5b9-e9c3d889bde5": {
        "username": "KodamaRei",
        "server": "jamming"
      }
    }
