apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-lobby-sv
resources:
  # namespace
  - ./ns-mc-lobby-sv.yaml
  # template
  - ../templates/minecraft-server
  # holograms
  - ./mc-lobby-plugin-holograms-configs.yaml

patches:
  - path: lobby-statefulset.yaml
  - path: mc-lobby-plugin-advancedportals-configs.yaml
