apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/latest"
            - name: WORLDGUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/latest"
            - name: SPAWN_URL
              value: "https://cdn.modrinth.com/data/Pw3KRjwE/versions/mgrZ4A8t/Spawn-2.4.1.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/Spawn-2.4.1.jar "${SPAWN_URL}"

        # ------minecraft lobbyのワールド生成関連------
        - name: download-world
          image: busybox:1.36.1
          env:
            - name: WORLD_URL
              value: "https://github.com/maron-gt123/k8s-setup-for-proxmox/releases/download/1.0/world.tar"
          volumeMounts:
            - name: world-download-volume
              mountPath: /root/world-download
          command:
            - sh
            - -c
            - >
              echo "start downloading world data" &&
              wget --no-check-certificate -qO /root/world-download/world.tar "${WORLD_URL}" &&
              tar -xvf /root/world-download/world.tar -C /root/world-download/ &&
              rm /root/world-download/world.tar &&
              echo "successfully imported world data"
      containers:
        - name: minecraft
          env:
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: SPAWN_ANIMALS
              value: "false"
            - name: SPAWN_MONSTERS
              value: "false"
            - name: SPAWN_NPCS
              value: "false"
            - name: CFG_ALLOW_END
              value: "false"
            # ------lobby用の変数設定 ------
            # ------LuckPermsのサーバー名 ------
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: lobby
            # ------lobby用コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
          volumeMounts:
            # ------lobby用ワールドマウント ------
            - name: world-download-volume
              mountPath: /data/world
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ worldedit ------
            - name: init-download-volume
              mountPath: /data/plugins/worldedit.jar
              subPath: worldedit.jar
            # ------ worldguard ------
            - name: init-download-volume
              mountPath: /data/plugins/worldguard.jar
              subPath: worldguard.jar
            # ------ Spawn ------
            - name: init-download-volume
              mountPath: /data/plugins/Spawn-2.4.1.jar
              subPath: Spawn-2.4.1.jar
            # ------lobby用configファイルマウント ------
            # ------ holograms-S1_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-S1_Gateway.yml
              subPath: holograms-S1_Gateway.yml
            # ------ holograms-S2_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-S2_Gateway.yml
              subPath: holograms-S2_Gateway.yml
            # ------ holograms-music_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-music-Gateway.yml
              subPath: holograms-music-Gateway.yml
            # ------ holograms-tohoku_Gateway ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms/holograms-tohoku_Gateway.yml
              subPath: holograms-tohoku_Gateway.yml
      volumes:
        - name: world-download-volume
          emptyDir: {}
