apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

# CRD は必ず先に適用される
crds:
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/Deploy/crds/tridentorchestrator_crd.yaml
resources:
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/Deploy/Trident/bundle.yaml
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/Deploy/Trident/tridentorchestrator.yaml
