apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: iscsi-storage          # 任意の StorageClass 名
provisioner: csi.trident.qnap.io
parameters:
  selector: "iqn=iqn.2004-04.com.qnap:ts-253d:iscsi.target-1.4bd441"
  fsType: ext4
allowVolumeExpansion: true
mountOptions:
  - discard
