apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ./argocd-server-lb.yaml
  - ./argocd-metrics-path.yaml
  - ./config/argocd-secret.yaml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: ./config/argocd-cm-patch.yaml