apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - https://github.com/argoproj/argo-cd/manifests/namespace-install?ref=stable
  - ./argocd-server-lb.yaml
  - ./argocd-metrics-path.yaml
patches:
  - patch: |-
      - op: add
        path: /data/resource.exclusions
        value: |
          - apiGroups:
              - cilium.io
            kinds:
              - CiliumIdentity
            clusters:
              - "*"
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm

  - patch: |-
      - op: add
        path: /stringData
        value:
          admin.password: $2y$10$mqhcbzPnSWTukQc2n.uUvecI9Tk0BFjeaPcdpBeFpnzTnq/wjQYuW
          admin.passwordMtime: "2026-04-18T00:00:00Z"
    target:
      version: v1
      kind: Secret
      name: argocd-secret