apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/VolumeSnapshot/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/VolumeSnapshot/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/VolumeSnapshot/snapshot.storage.k8s.io_volumesnapshots.yaml
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/VolumeSnapshot/rbac-snapshot-controller.yaml
  - https://raw.githubusercontent.com/qnap-dev/QNAP-CSI-PlugIn/refs/heads/main/VolumeSnapshot/setup-snapshot-controller.yaml
