{
 "title": "Minecraft-Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Statistic",
    "label": "Statistic",
    "query": {
     "query": "label_values(mc_player_statistic,statistic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "playerトータル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server_name) (mc_players_total)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "online player数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server_name) (mc_players_online_total)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "JVMメモリ数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=\"minecraft-server-lobby\"} - scalar(mc_jvm_memory{type='free', server_name=\"minecraft-server-lobby\"})",
     "legendFormat": "{{server_name}}"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=\"minecraft-server-S1\"} - scalar(mc_jvm_memory{type='free', server_name=\"minecraft-server-S1\"})",
     "legendFormat": "{{server_name}}"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=\"minecraft-server-S2\"} - scalar(mc_jvm_memory{type='free', server_name=\"minecraft-server-S2\"})",
     "legendFormat": "{{server_name}}"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=\"minecraft-server-k8s\"} - scalar(mc_jvm_memory{type='free', server_name=\"minecraft-server-k8s\"})",
     "legendFormat": "{{server_name}}"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=\"minecraft-server-music\"} - scalar(mc_jvm_memory{type='free', server_name=\"minecraft-server-music\"})",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(server_name) (mc_tps)", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_players_online_total)",
     "legendFormat": "オンライン数_({{server_name}})"
    }
   ]
  },
  {
   "title": "playerオンライン推移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(name)(mc_player_online) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "読み込みチャンク数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "count by(world, server_name) (mc_loaded_chunks_total)",
     "legendFormat": "{{world}} ({{server_name}})"
    }
   ]
  },
  {
   "title": "JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server_name) (mc_jvm_memory{type=\"max\"})",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated'} - scalar(mc_jvm_memory{type='free'}))",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated'})",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "villagers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(world, level, profession, server_name) (mc_villagers_total)",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}}) ({{server_name}})"
    }
   ]
  },
  {
   "title": "エンティティ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_entities_total)",
     "legendFormat": "{{world}}_total ({{server_name}})"
    }
   ]
  },
  { "title": "Serverごと", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "lobby_プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=\"minecraft-server-lobby\"})",
     "legendFormat": "{{server_name}}_{{world}}"
    }
   ]
  },
  {
   "title": "S1_プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=\"minecraft-server-S1\"})",
     "legendFormat": "{{server_name}}_{{world}}"
    }
   ]
  },
  {
   "title": "S2_プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=\"minecraft-server-S2\"})",
     "legendFormat": "{{server_name}}_{{world}}"
    }
   ]
  },
  {
   "title": "k8s_プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=\"minecraft-server-k8s\"})",
     "legendFormat": "{{server_name}}_{{world}}"
    }
   ]
  },
  {
   "title": "music_プレイヤー数遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "sum by(world, server_name) (mc_players_online_total{server_name=\"minecraft-server-music\"})",
     "legendFormat": "{{server_name}}_{{world}}"
    }
   ]
  },
  {
   "title": "lobby_JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server_name) (mc_jvm_memory{type=\"max\",server_name=\"minecraft-server-lobby\"})",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-lobby\"} - scalar(mc_jvm_memory{type='free',server_name=\"minecraft-server-lobby\"}))",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-lobby\"})",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "S1_JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server_name) (mc_jvm_memory{type=\"max\",server_name=\"minecraft-server-S1\"})",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-S1\"} - scalar(mc_jvm_memory{type='free',server_name=\"minecraft-server-S1\"}))",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-S1\"})",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "S2_JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server_name) (mc_jvm_memory{type=\"max\",server_name=\"minecraft-server-S2\"})",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-S2\"} - scalar(mc_jvm_memory{type='free',server_name=\"minecraft-server-S2\"}))",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-S2\"})",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "k8s_JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server_name) (mc_jvm_memory{type=\"max\",server_name=\"minecraft-server-k8s\"})",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-k8s\"} - scalar(mc_jvm_memory{type='free',server_name=\"minecraft-server-k8s\"}))",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-k8s\"})",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  {
   "title": "music_JVMメモリ遷移",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server_name) (mc_jvm_memory{type=\"max\",server_name=\"minecraft-server-music\"})",
     "legendFormat": "最大値 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-music\"} - scalar(mc_jvm_memory{type='free',server_name=\"minecraft-server-music\"}))",
     "legendFormat": "使用中 ({{server_name}})"
    },
    {
     "expr": "sum by (server_name)(mc_jvm_memory{type='allocated',server_name=\"minecraft-server-music\"})",
     "legendFormat": "割当中 ({{server_name}})"
    }
   ]
  },
  { "title": "ユーザ関連詳細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "$Statistic over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(player_name,statistic,server_name)(mc_player_statistic{statistic=~\"$Statistic\"}) ",
     "legendFormat": "{{player_name}}: {{server_name}}"
    }
   ]
  },
  {
   "title": "$Statistic by player",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(player_name,server_name) (mc_player_statistic{statistic=\"$Statistic\"})",
     "legendFormat": "{{player_name}}: {{server_name}}"
    }
   ]
  }
 ]
}