apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    spec:
      initContainers:
      containers:
        - name: minecraft
          resources:
            requests:
              cpu: "2"
              memory: 4096M
          env:
            # ---- 基本設定 ---- 
            - name: VERSION
              value: "26.1.2"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 4096M
            - name: EULA
              value: "TRUE"
            - name: PLUGINS
              value: >-
                https://cdn.modrinth.com/data/axTqSWQA/versions/SqR0biky/Advanced-Portals-Spigot-2.6.1.jar,
                https://download.luckperms.net/1631/bukkit/loader/LuckPerms-Bukkit-5.5.42.jar,
                https://server-backup.net/assets/downloads/ServerBackup-2.10.0.jar
            # ---- server configの変数 ---- 
            - name: ENABLE_RCON
              value: "true"
            - name: DIFFICULTY
              value: easy
            - name: LEVEL_TYPE
              value: normal
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mcserver
                  key: CFG_MC_RCON_PASSWORD
            - name: SPIGET_RESOURCES
              value: 
            - name: RCON_CMDS_STARTUP
              value: |-
          ports:
            - name: mc-service
              containerPort: 25565
            - name: mc-rcon
              containerPort: 25575
            - name: mc-metrics
              containerPort: 9225
          volumeMounts:
            # ------- init-file mount -------
            - name: init-download-volume
              mountPath: /jmx-exporter/jmx-exporter-javaagent.jar
              subPath: jmx-exporter-javaagent.jar
            - name: jmx-exporter-config
              mountPath: /jmx-exporter/jmx-exporter-config.yaml
              subPath: jmx-exporter-config.yaml
            # ------- paper-config mount -------
            - name: paper-config
              mountPath: /config/config/
            # ------- prometeus-exporter mount -------
            - name: prometheus-exporter-config
              mountPath: /config/plugins/PrometheusExporter/config.yml
              subPath: prometheus-exporter-config.yml
            # ------- serverbackup mount -------
            - name: serverbackup-config
              mountPath: /config/plugins/ServerBackup/config.yml
              subPath: serverbackup.yml
      volumes:
        # ------- serverbackupのvolume -------
        - name: serverbackup-config
          configMap:
            name: serverbackup-config
