apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-world-pvc
  labels:
    app: java-world-pvc
spec:
  volumeName: java-world-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi