apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft-debug
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
      containers:
        - image: itzg/minecraft-server:java21
          name: minecraft
          env:
            - name: REPLACE_ENV_VARIABLE_PREFIX #0
              value: CFG_
            - name: EULA #1
              value: "TRUE"
            - name: TZ #2
              value: Asia/Tokyo
            - name: TYPE #3
              value: PAPER
            - name: VERSION #4
              value: "1.21.8"
            - name: INIT_MEMORY #5
              value: 1G
            - name: MAX_MEMORY #6
              value: 2G
            - name: ENABLE_RCON #7
              value: "true"
            - name: ONLINE_MODE #10
              value: "false"
            - name: PLUGINS #31
              # フルpathのpluginが公開されているものはここで直接ダウンロードし/data/pluginsに格納
              # ServerBackup
              # minecraft-prometheus-exporter3.1.0
              # LuckPerms-Bukkit5.4.137
              # Advanced-Portals-0.9.3
              # LunaChat
              # DiscordSRV
              value: >-
                https://server-backup.net/assets/downloads/ServerBackup-2.10.0.jar,
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.2/minecraft-prometheus-exporter-3.1.2.jar,
                https://download.luckperms.net/1595/bukkit/loader/LuckPerms-Bukkit-5.5.10.jar,
                https://cdn.modrinth.com/data/axTqSWQA/versions/I8wYnsdu/Advanced-Portals-Spigot-2.5.0.jar,
                https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar,
                https://github.com/DiscordSRV/DiscordSRV/releases/download/v1.30.0/DiscordSRV-Build-1.30.0.jar
            # config関連を/configから/dataへmcopy
            - name: COPY_CONFIG_DEST #33
              value: /data
            - name: RCON_CMDS_STARTUP #34
              value: |-

          ports:
            - name: mc-service
              containerPort: 25565
            - name: mc-recon
              containerPort: 25575
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            # world関連の格納先マウント
            - name: data
              mountPath: /data
      volumes:
        # paperのボリューム
        - name: data
          emptyDir: {}
        # initContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: init-download-volume
          emptyDir: {}
